name: docs_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - atk=2.36.0
  - atk-1.0=2.36.0
  - blosc=1.21.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cairo=1.16.0
  - cfitsio=3.470
  - chrpath=0.16
  - curl=7.76.1
  - dbus=1.13.6
  - dcw-gmt=2.2.0
  - expat=2.7.1
  - ffmpeg=4.4.0
  - fftw=3.3.10
  - fontconfig=2.14.2
  - freetype=2.12.1
  - freexl=1.0.6
  - fribidi=1.0.16
  - gdal=3.0.4
  - gdk-pixbuf=2.42.2
  - geos=3.8.1
  - geotiff=1.5.1
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - ghostscript=10.06.0
  - giflib=5.2.2
  - glib=2.66.3
  - gmp=6.3.0
  - gmt=6.0.0
  - gnuplot=5.2.7
  - gnutls=3.6.13
  - gobject-introspection=1.66.1
  - graphicsmagick=1.3.35
  - graphite2=1.3.14
  - gshhg-gmt=2.3.7
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gtk2=2.24.32
  - harfbuzz=2.4.0
  - hdf4=4.2.15
  - hdf5=1.10.5
  - icu=64.2
  - jpeg=9e
  - json-c=0.13.1
  - kealib=1.4.13
  - keyutils=1.6.3
  - krb5=1.17.2
  - lame=3.100
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libarchive=3.5.1
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.9.0
  - libboost-headers=1.89.0
  - libcblas=3.9.0
  - libclang=9.0.1
  - libcurl=7.76.1
  - libdap4=3.20.6
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.2.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgd=2.2.5
  - libgdal=3.0.4
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.66.3
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=2.1.4
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm9=9.0.1
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.7.4
  - libnghttp2=1.51.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libpng=1.6.43
  - libpq=12.3
  - librttopo=1.1.0
  - libspatialite=4.3.0a
  - libsqlite=3.46.0
  - libssh2=1.10.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.1.0
  - libuuid=2.41.2
  - libvpx=1.11.0
  - libwebp=1.0.2
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - libzlib=1.2.13
  - lz4-c=1.9.2
  - lzo=2.10
  - minizip=1.2
  - ncurses=6.5
  - nettle=3.6
  - nspr=4.37
  - nss=3.100
  - numpy=1.24.4
  - openh264=2.1.1
  - openjpeg=2.3.1
  - openssl=1.1.1w
  - pango=1.42.4
  - pcre=8.45
  - pcre2=10.43
  - pip=24.3.1
  - pixman=0.38.0
  - poppler=0.67.0
  - poppler-data=0.4.12
  - postgresql=12.3
  - proj=7.0.0
  - pthread-stubs=0.4
  - python=3.8.6
  - python_abi=3.8
  - qt=5.12.5
  - readline=8.2
  - setuptools=75.3.0
  - snappy=1.1.10
  - sqlite=3.46.0
  - tbb=2020.2
  - tiledb=1.7.0
  - tk=8.6.13
  - tzcode=2025b
  - uriparser=0.9.8
  - wheel=0.45.1
  - x264=1!161.3030
  - xerces-c=3.2.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.2.13
  - zstd=1.4.8
  - pip:
      - alabaster==0.7.13
      - babel==2.17.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - docutils==0.18.1
      - fonttools==4.57.0
      - idna==3.11
      - imagesize==1.4.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - lumache==0.1.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - myst-parser==3.0.1
      - packaging==25.0
      - pandas==2.0.3
      - pillow==10.4.0
      - pygments==2.19.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.4
      - six==1.17.0
      - snowballstemmer==3.0.1
      - sphinx==7.1.2
      - sphinx-rtd-theme==1.3.0rc1
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - tzdata==2025.2
      - urllib3==2.2.3
      - zipp==3.20.2
prefix: /home/users/mmanoj/miniconda3/envs/docs_env
